### ISSUE TITLE
[Meta] PHP 7.1 features

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#2090]
PHP 7.1.0 Beta 1 is [released](http://php.net/archive/2016.php#id2016-07-21-1) with a [feature stop](https://www.reddit.com/r/PHP/comments/4tw8m0/php_710_beta_1_released/d5ks9e6) so we can list the things we need to take care of or could support.
- [ ] `void` return type [RFC](https://wiki.php.net/rfc/void_return_type)
- [ ] `Iterable` pseudo-type accepting any array or object implementing `Traversable` [RFC](https://wiki.php.net/rfc/iterable)
- [x] Support Class Constant Visibility [RFC](https://wiki.php.net/rfc/class_const_visibility)
- [x] Added a form of the `list()` construct where keys can be specified [RFC](https://wiki.php.net/rfc/list_keys)
- [x] Added `[] =` as alternative construct to `list() =` [RFC](https://wiki.php.net/rfc/short_list_syntax)
- [x] Added `nullable` types. [RFC](https://wiki.php.net/rfc/nullable_types)
- [x] String offset access now supports negative references, which will be counted from the end of the string [RFC](https://wiki.php.net/rfc/negative-string-offsets)
- [x] ASCII 0x7F delete control character is no longer permitted in unquoted identifiers in source code
- [x] multiple catch [RFC](https://wiki.php.net/rfc/multiple-catch)
- [x] rand() aliased to mt_rand() and srand() aliased to mt_srand()

Sources:
https://github.com/php/php-src/blob/php-7.1.0beta1/NEWS
https://github.com/php/php-src/blob/php-7.1.0beta1/UPGRADING

Thanks to all who worked on PHP7.1!

**Comment by SpacePossum** [comment]
ping @dshafik it seems the support for class constant visibility is missing from;
https://github.com/php/php-src/blob/php-7.1.0beta1/UPGRADING
it is listed in https://github.com/php/php-src/blob/php-7.1.0beta1/NEWS#L373 (PHP 7.1.0alpha1).
Am I correct to assume it will still be part of 7.1?

**Comment by keradus** [comment]
I Added multiple-catch  to the list

**Comment by SpacePossum** [comment]
perfect, filling in the blanks :)

**Comment by HeahDude** [comment]
Also, it seems that the fixer for spaces in ternary condition also adds a space in nullable type hints :(

**Comment by keradus** [comment]
>  Added nullable types. RFC

we didn't add support for them yet. feel free to contribute !

**Comment by HeahDude** [comment]
@keradus Yes I'm just saying that it needs to update a current fixer too :)

**Comment by keradus** [comment]
we do sth like `https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/master/tests/Fixtures/Integration/misc/PHP7.test` so we try to figure out which fixers need to be updated as well for new syntax.

**Comment by HeahDude** [comment]
Thanks for the heads-up ;)

**Comment by keradus** [comment]
I think that thanks to #2196 and #2205 the `iterable` support is there. Please verify @SpacePossum

**Comment by SpacePossum** [comment]
I think we miss the logic to fix the casing of `iterable` in (return) type hinting? not sure though I haven't checked as I messed up my PHP7.1 VM ATM.

**Comment by keradus** [comment]
Do we have a fixer for that in first place? I don't think so

**Comment by SpacePossum** [comment]
Don't think so either, having case-fixing-fixers for std-classes and interfaces would be nice though.
Anyway, with that in mind I leave it to others to make the call if we have support for `iterable` or not :)

**Comment by GrahamCampbell** [comment]
How many of these fixers destroy the codebase with the new syntax? For now, could we skip bad cases until they're properly implemented?

**Comment by keradus** [comment]
go ahead and check it / skip it / fix it

**Comment by GrahamCampbell** [comment]
What I was really asking is if anyone's aware of anything really broken. I guess I'll find out. :)

**Comment by keradus** [comment]
what has been reported was already fixed ;)

**Comment by curry684** [comment]
Optional parameters are still pretty much broken, is anyone working on that?

Also, even with `-vvv` it only shows the linting failed, not how and where. Got me confused at first.

**Comment by SpacePossum** [comment]
>Optional parameters are still pretty much broken, is anyone working on that?

not that I'm aware of, so please help :)

>Also, even with `-vvv` it only shows the linting failed, not how and where. Got me confused at first.

Hits me as well once and awhile, would be great to improve the reporting. For linting we do rely on the runtime (i.e. PHP or HHVM), would be worth it to check out if we can retrieve more details from it when linting fails.

**Comment by curry684** [comment]
Hmm just started looking into it when I realized my test case is completely invalid - the linting was failing because my local Ubuntu is running PHP 7.0 but I'm running a 7.1 application inside Docker. Might have another look at this later on.

The hidden linter errors should be pretty easy to fix, they're just being eaten at `Runner.php:144`. The `LintingException` there contains the actual PHP parser error, in my case `"PHP Parse error: syntax error, unexpected '?' on line 179."`. That's pretty much all you need.

**Comment by keradus** [comment]
Strongly disagree. if they would not be handled there, they would break the flow and not allow to properly fix all other files. Solution would be to pass more information to ErrorManager

**Comment by curry684** [comment]
There's no disagreement, I didn't propose not *catching* the exception there, I said they were being *eaten* there. The details just need to be logged properly.

**Comment by keradus** [comment]
so, we do sth useful with it - catch it and handling it, only thing is that one would want to see more information about it.
anyway, nothing related to php 7.1

**Comment by curry684** [comment]
True that, moved to a separate issue.

**Comment by SpacePossum** [comment]
I'm closing the meta ticket as the vast majority has been done; patching fixers to not break code, new rules, etc. 
There might be more cases we could support _better_ and for this I would like you all to open dedicated tickets.
Thanks!

**Comment by Jean85** [comment]
This issue is linked as a blocker in #2512, but it seems done to me... The opening comments has `void` and `Iterable` as unchecked stuff, but I see:
 * #2740 done (but not merged?) for void
 * `Iterable` not done
Cna we have more details so we can help on these matters?

**Comment by SpacePossum** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2512 is about supporting PHP7.2 this issue is about 7.1.
We support PHP7.1 for a while (7.2 was dropped here https://github.com/FriendsOfPHP/PHP-CS-Fixer/commit/d6ec4dd3e8d5b79995b8b45fe904c58b9eb3fce9#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780R17 ), which is why this issue is clossed.
Please discuss PHP 7.2 @ https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/2907
