### ISSUE TITLE
[Meta] PHP 7.4 support 

### ISSUE THREAD

**Issue by SpacePossum** [FriendsOfPHP/PHP-CS-Fixer#4382]
#### (Syntax) changes that require new tests to make sure the tool is compatible with PHP 7.4:

- [x] [Null Coalescing Assignment Operator](https://wiki.php.net/rfc/null_coalesce_equal_operator) (#4603)
- [x] [Typed Properties 2.0](https://wiki.php.net/rfc/typed_properties_v2) (#4593)
- [x] [Spread Operator in Array Expression](https://wiki.php.net/rfc/spread_operator_for_array) (#4602)
- [x] [Arrow Functions 2.0](https://wiki.php.net/rfc/arrow_functions_v2) (#4600)
- [x] [Change the precedence of the concatenation operator](https://wiki.php.net/rfc/concatenation_precedence) (couldn't find any issue with this on 2.15)
- [x] [Numeric Literal Separator](https://wiki.php.net/rfc/numeric_literal_separator) (#4596)

#### Other:

- [x] [Reflection for references](https://wiki.php.net/rfc/reference_reflection) (class casing) (couldn't find any issue with this on 2.15)
- [x] [Password Hashing Registry](https://wiki.php.net/rfc/password_registry) (function casing) (couldn't find any issue with this on 2.15)
- [x] [mb_str_split](https://wiki.php.net/rfc/mb_str_split) (#4380 -> #4534)
- [x] [New custom object serialization mechanism](https://wiki.php.net/rfc/custom_object_serialization) (#4381)

### TODO:

- [x] PHP 7.4 integration test (#4637)
- [x] do the same checks for rules added in v2.16 (#4638)
- [x] do the same checks for rules added on master (couldn't find any issue with this on master)
- [x] VisibilityRequiredFixer (#4641)

#### Sources:
[Approved RFC's list for PHP7.4](https://wiki.php.net/rfc#php_74)

**Comment by zmitic** [comment]
Will it be possible to automatically add property typehints if constructor has assignment, but property itself doesn't have ``@var`` annotation?

Example:

```php
class Product
{
	private $category;

	public function __construct(Category $category)
	{
		$this->category = $category;
	}
}
```

The reason is that I never put ``@var`` annotations, PHPStorm is smart enough to figure the type from constructor and give me autocomplete.

**Comment by keradus** [comment]
can be problematic in cases like
```php
        private $foo;
	public function __construct(Category $category)
	{
		$this->foo = validateCategory($category) ? $category : createDummyCategory();
	}
```
i know, stupid code, but possible.

PHP CS Fixer is not going that deep into looking on code execution

**Comment by JarJak** [comment]
Those should check first PHP version installed, no? Just got `str_split` replaced with `mb_str_split` on PHP 7.2...

**Comment by julienfalque** [comment]
I checked _Deprecate left-associative ternary operator_ item as I don't think we have anything to do for it (it does not introduce any syntax change).

**Comment by julienfalque** [comment]
I checked every item of the list: all seem ok to me or have a corresponding PR to improve support. Please review :)

Note that merging those PRs should allow us to claim support for PHP 7.4 on branch 2.15 only. We still need to do the same checks on master for new fixers that have been added.

**Comment by keradus** [comment]
can you take a look at higher branches, @julienfalque , please ?

**Comment by keradus** [comment]
It took us quite a while, but i'm supper happy we have it now, just before 7.4 official release at 28th of Nov

**Comment by brendt** [comment]
Is there any documentation available on how to use these new PHP 7.4 feautres?

**Comment by artyom-wcd** [comment]
i am also interested, how to use new features?

**Comment by julienfalque** [comment]
This issue was not about implementation of new features for PHP 7.4 but to make sure that *existing* features were compatible with new PHP 7.4 syntax changes.

**Comment by SpacePossum** [comment]
see also https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4834 for the introduction of the PHP7.4 rule sets to easy migration
