### ISSUE TITLE
PHP 8.0 support

### ISSUE THREAD

**Issue by julienfalque** [FriendsOfPHP/PHP-CS-Fixer#4702]
#### Syntax changes that require new tests to make sure the tool is compatible with PHP 8.0:

- [Named Arguments](https://wiki.php.net/rfc/named_params)
  - [x] update existing code => integration test in #5399
  - [ ] new feature
- [Nullsafe operator](https://wiki.php.net/rfc/nullsafe_operator)
  - [x] update existing code => integration test in #5399
  - [ ] new feature
- Attributes ([Attributes v2](https://wiki.php.net/rfc/attributes_v2), [Attribute Amendments](https://wiki.php.net/rfc/attribute_amendments), [Shorter Attribute Syntax](https://wiki.php.net/rfc/shorter_attribute_syntax) and [Shorter Attribute Syntax Change](https://wiki.php.net/rfc/shorter_attribute_syntax_change))
  - [x] update existing code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5284)
  - [ ] new feature
- [Union Types 2.0](https://wiki.php.net/rfc/union_types_v2)
  - [x] update existing code => integration test in #5399
  - [ ] new feature
- [Allow ::class on objects](https://wiki.php.net/rfc/class_name_literal_on_object)
  - [x] update existing code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5166)
  - [ ] new feature
- [Static return type](https://wiki.php.net/rfc/static_return_type)
  - [x] update existing code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5177, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5184)
  - [x] new feature (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5177, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5184)
- [Variable Syntax Tweaks](https://wiki.php.net/rfc/variable_syntax_tweaks)
  - [x] ~~update existing code~~
  - [ ] new feature
- [Allow trailing comma in parameter list](https://wiki.php.net/rfc/trailing_comma_in_parameter_list)
  - [x] ~update existing code~ (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5240 https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5239)
  - [x] new feature
- [Allow trailing comma in closure use lists](https://wiki.php.net/rfc/trailing_comma_in_closure_use_list)
  - [x] ~~update existing code~~
  - [ ] new feature
- [Mixed Type v2](https://wiki.php.net/rfc/mixed_type_v2)
  - [x] update existing code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5254)
  - [ ] new feature
- [throw expression](https://wiki.php.net/rfc/throw_expression)
  - [x] update existing code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5232)
  - [ ] new feature
- [non-capturing catches](https://wiki.php.net/rfc/non-capturing_catches)
  - [x] ~~update existing code~~
  - [ ] new feature (WIP https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5175)
- [Constructor Property Promotion](https://wiki.php.net/rfc/constructor_promotion)
  - [x] update existing code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5277)
  - [ ] new feature
- [Match expression v2](https://wiki.php.net/rfc/match_expression_v2)
  - [x] update existing code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5251)
  - [ ] new feature
- [Add str_starts_with() and str_ends_with() functions](https://wiki.php.net/rfc/add_str_starts_with_and_ends_with_functions)
  - [x] ~~update existing code~~
  - [x] new feature
- [Add str_contains() function](https://wiki.php.net/rfc/str_contains)
  - [x] new feature
- [Deprecate curly brace syntax for accessing array elements and string offsets](https://wiki.php.net/rfc/deprecate_curly_braces_array_access)
  - [x] ~~update existing code~~
  - [x] ~~new feature~~ (already implemented)
- [Change the precedence of the concatenation operator](https://wiki.php.net/rfc/concatenation_precedence)
  - [x] update existing code
  - [ ] new feature
- [Remove inappropriate inheritance signature checks on private methods](https://wiki.php.net/rfc/inheritance_private_methods)
  - [x] ~~update existing code~~
  - [x] ~~new feature~~ (already implemented)
- [Deprecate left-associative ternary operator](https://wiki.php.net/rfc/ternary_associativity)
  - [x] ~~update existing code~~
  - [ ] new feature
- [Add Stringable interface](https://wiki.php.net/rfc/stringable)
  - [x] update existing code (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5166)
  - [ ] new feature
- Date: mktime() and gmmktime() now require at least one argument. time() can be used to get the current timestamp.
  - [x] ~~update existing code~~
  - [x] new feature (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5166)
- Exif: Removed read_exif_data(). exif_read_data() should be used instead.
  - [x] ~~update existing code~~
  - [x] new feature (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5166)
- The imap_header() function which is an alias of imap_headerinfo() has been removed.
  - [x] ~~update existing code~~
  - [x] ~~new feature~~ (already implemented)
- parse_str() can no longer be used without specifying a result array.
  - [x] ~~update existing code~~
  - [x] ~~new feature~~ (not we can do)
- Calling implode() with parameters in a reverse order ($pieces, $glue) is no longer supported.
  - [x] ~~update existing code~~
  - [x] ~~new feature~~ (already implemented)
- Mbstring A number of deprecated mbregex aliases have been removed.
  - [x] ~~update existing code~~
  - [x] ~~new feature~~ (already implemented)
- Namespaced names can no longer contain whitespace (nor comments)
  - [x] ~~update existing code~~
  - [x] new feature (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5264)
- [x] PHP 8.0 migration rule set (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5166)
- [x] PHP 8.0 integration test (`tests/Fixtures/Integration/misc/PHP8_0.test`) ensuring all new syntaxes are passing complex ruleset like `@Symfony` or `@PhpCsFixer:risky`) (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5399)
- [x] Update ~Travis~ GitHub Actions with dedicated PHP8 job

```
- GMP:
  . gmp_random() has been removed. One of gmp_random_range() or
    gmp_random_bits() should be used instead.
```

```
- OCI8:
  . The OCI-Lob class is now called OCILob, and the OCI-Collection class is now
    called OCICollection for name compliance enforced by PHP 8 arginfo
    type annotation tooling.
  . Several alias functions have been marked as deprecated.
```

```
- Reflection:
  . The method signatures
        ReflectionClass::newInstance($args)
        ReflectionFunction::invoke($args)
        ReflectionMethod::invoke($object, $args)

    have been changed to:
        ReflectionClass::newInstance(...$args)
        ReflectionFunction::invoke(...$args)
        ReflectionMethod::invoke($object, ...$args)

    Code that must be compatible with both PHP 7 and PHP 8 can use the following
    signatures to be compatible with both versions:
        ReflectionClass::newInstance($arg = null, ...$args)
        ReflectionFunction::invoke($arg = null, ...$args)
        ReflectionMethod::invoke($object, $arg = null, ...$args)
```

#### Other changes that might require fixing existing tests and/or adding new ones:

- [x] ~~[Object-based token_get_all() alternative](https://wiki.php.net/rfc/token_as_object)~~
- [x] [Treat namespaced names as single token](https://wiki.php.net/rfc/namespaced_names_as_token) (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5166)
- [x] ~~[Don't include trailing newline in comment token](https://github.com/php/php-src/pull/5182)~~
- [x] SPL: SplFixedArray is now an IteratorAggregate and not an Iterator. (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5166)

Additional source: https://github.com/php/php-src/blob/php-8.0.0rc1/UPGRADING

#### Note
- From now we only accept PR's that are compatible with PHP8 
- Updating `composer.json` of the project will be done after all current functionality has been made compatible (new feature support can wait)
- We will keep the build step `nightly` as allowed to fail. When there is a dedicated Travis target for PHP8 we will add it to the steps

**Comment by mvorisek** [comment]
Union Types rule should definitely support sorting to prevent `!n` possible orders.

**Comment by julienfalque** [comment]
Note that this issue is not about implementing new rules but making sure that existing rules do not break with new PHP 8.0 syntax changes. Nice suggestion though :+1:

**Comment by SpacePossum** [comment]
these will be in PHP8 and effect us (I think)
https://wiki.php.net/rfc/class_name_literal_on_object
https://wiki.php.net/rfc/static_return_type
https://wiki.php.net/rfc/variable_syntax_tweaks

**Comment by GrahamCampbell** [comment]
More changes to the lexer: https://github.com/sebastianbergmann/php-token-stream/issues/95.

**Comment by SpacePossum** [comment]
added alias in PHP8

https://wiki.php.net/rfc/rename-double-colon-token

**Comment by GrahamCampbell** [comment]
@SpacePossum that RFC has been rejected. Voting closed yesterday, and they failed to get a 2/3 majority (only managed 58.9%).

**Comment by hamdrew** [comment]
@GrahamCampbell can you link the RFC?  php/php-src#5182 appears to be accepted and merged (despite the closed PR status).

**Comment by hamdrew** [comment]
Would a dedicated Travis CI job for PHP 8.0 be a part of the definition of done for this issue? I know there is a "nightly builds" job, but that is different than pointing to a release of PHP 8.0 (even if it is beta).

**Comment by julienfalque** [comment]
> Would a dedicated Travis CI job for PHP 8.0 be a part of the definition of done for this issue?

If Travis CI supports dedicated PHP 8.0 jobs, I would say yes.

**Comment by GrahamCampbell** [comment]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5114 gets us started with some stuff. If anyone could work out why that\s not working, that'd be a help.

**Comment by hamdrew** [comment]
[PHP 8.0 Wiki Page and Timetable](https://wiki.php.net/todo/php80) - **GA Release 11/26/2020**

[PHP 8.0.0RC1 Upgrade Notes](https://github.com/php/php-src/blob/php-8.0.0rc1/UPGRADING)

**Comment by hamdrew** [comment]
I took some time to review all the core changes in the upgrade notes and their respective RFCs. I picked out the ones that had syntax changes, or I otherwise felt might break a rule.  

I created a Google Sheet to track these potentially rule-breaking changes.  Anyone can comment on this sheet. Please request edit permissions if desired:

https://docs.google.com/spreadsheets/d/1URgmC3lM34AKQmllDJlh3dmXU95EaixqowATSKFTX90/edit?usp=sharing

This is just a quick-and-dirty organization technique for myself that I thought would be useful; if there is a better place to organize this (GitHub issue?) let me know.

**Comment by julienfalque** [comment]
@hamdrew To be honest I prefer tracking PHP changes here, I updated the description. Hopefully I didn't forget anything important.

**Comment by hamdrew** [comment]
@julienfalque I agree! I removed the link to avoid confusion.

Last night I set up a PHP 8 docker environment to develop from. I share it here if anyone finds it useful: https://github.com/hamdrew/PHP-CS-Fixer-Docker

I didn't want to contribute a docker development environment directly to this project because that is a large discussion that doesn't need to happen right now.

**Comment by hamdrew** [comment]
I addressed the SplFixedArray issue first in #5167, since it was prohibiting a lot of tests from running. 

@SpacePossum To what branch would you like php8-related PRs to be targeted?  I chose *master* for now.

**Comment by SpacePossum** [comment]
Thanks @hamdrew for the work in the PR!
Currently I'm working in PHP8 support as well in https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5166 , for now I picked 2.15 to see what we can do for as many as branches we support.

**Comment by hamdrew** [comment]
@SpacePossum Cool, I'll target the same branch in my PRs to be consistent.

**Comment by GrahamCampbell** [comment]
Related: https://github.com/PHP-CS-Fixer/diff/issues/19.

**Comment by viezel** [comment]
Would it be possible to bump this package from `"php": "^5.6 || ^7.0",` to `"php": "^5.6 || ^7.0 || ^8.0",` in order not to block other package. Atm `php-webdriver/php-webdriver` is blocked among others. 

I understand that this issue tackle a larger overhaul, but would be great to get out of the blocking situation.

**Comment by SpacePossum** [comment]
From the description:

```
Note
Updating composer.json of the project will be done after all current functionality has been made compatible (new feature support can wait)
```

We are not going to break the code of our users, so "no" for now

**Comment by viezel** [comment]
@SpacePossum absolutely. I was not proposing to break anything. 

Will it be possible to view a list of the current functionality that is not compatible with 8?

**Comment by julienfalque** [comment]
@viezel Please read the original post of this thread.

The best fix for your issue is to **not** depend directly on PHP CS Fixer at all, not even in `require-dev`. Install it separately instead, e.g.:
```console
$ mkdir -p tools/php-cs-fixer
$ composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer
```
Unless you develop some extension for it, PHP CS Fixer is not a dependency of your code but a tool.

**Comment by GrahamCampbell** [comment]
There is also a nice vendor-bin plugin for composer which does this too.

**Comment by GrahamCampbell** [comment]
See, for example: https://github.com/vlucas/phpdotenv.

**Comment by vincentchalamon** [comment]
For GitHub Actions, php-cs-fixer can be easily installed thanks to [shivammathur/setup-php](https://github.com/shivammathur/setup-php/#wrench-tools-support) even on PHP 8

**Comment by keradus** [comment]
folks, be aware that PHP CS Fixer does not let itself to be installed on PHP 8 not because we are willing to add some extra feature that will improve PHP 8 syntax, but because if you run PHP CS Fixer and feed it with code written in PHP 8, tool itself can crash, or worse - it will not crash and write back to your PHP file with invalid syntax, as PHP CS Fixer is not yet fully aware about syntax changes brought bu PHP 8

**Comment by GrahamCampbell** [comment]
NB Executing php-cs-fixer on PHP 8.0 is not officially supported yet, so use with care!

**Comment by viezel** [comment]
> @viezel Please read the original post of this thread.
> 
> The best fix for your issue is to **not** depend directly on PHP CS Fixer at all, not even in `require-dev`. Install it separately instead, e.g.:
> 
> ```
> $ mkdir -p tools/php-cs-fixer
> $ composer require --working-dir=tools/php-cs-fixer friendsofphp/php-cs-fixer
> ```
> 
> Unless you develop some extension for it, PHP CS Fixer is not a dependency of your code but a tool.

I totally agree. But I do not control the https://github.com/php-webdriver/php-webdriver repo.

**Comment by GrahamCampbell** [comment]
It's on a dev-dep, so doesn't block you installing it. It blocks them testing on PHP 8 however. They should remove it from their require-dev, as per the suggestions in the above comments here.

**Comment by christeredvartsen** [comment]
> For GitHub Actions, php-cs-fixer can be easily installed thanks to shivammathur/setup-php even on PHP 8

@vincentchalamon This does not seem to be the case, at least not any more. I'm getting the following error when trying to include `8.0` in my build matrix, and pinning `php-cs-fixer` to `2.16.7` with the `shivammathur/setup-php` action:

> PHP needs to be a minimum version of PHP 7.1.0 and maximum version of PHP 7.4.*.

**Comment by canvural** [comment]
@christeredvartsen If you want to disable that check you can use `PHP_CS_FIXER_IGNORE_ENV=1` I don't know the consequences of this, so use with caution, but it will work with PHP 8 :smile:

**Comment by christeredvartsen** [comment]
@canvural Thanks, works in my case. Guess I'll keep an extra set of eyes on this build step until php-cs-fixer officially supports PHP 8.0. Thanks for the tip!

**Comment by MatTheCat** [comment]
> [Named Arguments](https://wiki.php.net/rfc/named_params)

WDYT of an `OptionalArgumentsFixer` which would remove arguments whose value is their default’s?

```
<?php chunk_split('This should be changed', 76);
```

would become

```
<?php chunk_split('This should be changed');
```

An additional boolean `name_arguments` option could determine whether

```
<?php chunk_split('This may be changed', 76, "\n");
```

would stay unchanged or become

```
<?php chunk_split('This should be changed', end: "\n");
```

**Comment by keradus** [comment]
due to changes in PHP parser and syntax, running PHP CS Fixer under PHP 8 can change meaning of your code (While tool itself will not crash, as code syntax is still valid after the change, yet it's meaning is different). Be warned when using `PHP_CS_FIXER_IGNORE_ENV=1`.

**Comment by keradus** [comment]
@MatTheCat for new feature requests, please raise dedicated issue or send a PR

**Comment by maicol07** [comment]
Hi, is there a beta or development version/branch where I can install PHP CS Fixer with PHP 8?

**Comment by BenMorel** [comment]
This issue is 1 year old, and seems to be far from complete. Is there any ETA on availability of a release compatible with PHP 8?
PHP CS Fixer is currently preventing us from upgrading to PHP 8, and I'd hate to have to remove it :/

**Comment by SeinopSys** [comment]
Welcome to open source @BenMorel, if you are that dependent on the project maybe consider supporting the developer financially, e.g. via [GitHub sponsorship](https://github.com/sponsors/keradus). It is also worth noting that PHP 8 has only been fully released for a bit over a week ago, so maybe have some patience?

**Comment by RVxLab** [comment]
@BenMorel If I understood this thread correctly you can use `PHP_CS_FIXER_IGNORE_ENV=1` to bypass the version constraint. Use at your own risk.

**Comment by BenMorel** [comment]
Sorry, I didn't mean to be rude, I also maintain [a couple open source projects](https://github.com/brick/math) myself, and I do understand that it's a lot of time investment. Let me simply rephrase my question as:

> When can we expect a PHP 8 -compatible release?

**Comment by keradus** [comment]
The effort needed to have basic support of new syntax (so to only understand it and don't break the code, not talking about effort to write new rules to adjust new syntax) is insane, for that, there is now ETA for PHP 8 support release.
I understand that this is not best situation, but amount of folks investing their private, free time is very limited.
If you want to speed up PHP 8 support, please take a look at TODO in opening message and help with one of it.

**Comment by SpacePossum** [comment]
composer install on PHP8 is now possible with the release of 2.17:
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5326

**Comment by GrahamCampbell** [comment]
For people complaining that PHP 8 doesn't work, remember this is an OSS project. It is much your job to make it work as it is anyone elses'. If you need a feature, consider implementing it yourself or asking for a quote for someone else to do it for you.

**Comment by SanderSander** [comment]
Based on the reasoning to not allow usage of the tool in #5341 

> The result running PHP CS Fixer on code with it is not known, currently.
> We already had a case when PHP 8 code was parsed, changed by fixer and produced valid PHP syntax, but with different meaning. We don't want to offer that to users of the tool. In our opinion it's better to not offer the tool than offer the tool and break the code logic.

Would it be an idea to give the user a warning when someone uses php-cs-fixer with PHP 8.0

**Comment by keradus** [comment]
or at least the info how to use PHP_IGNORE_ENV.
would you mind to add that note, @SanderSander ?

**Comment by SanderSander** [comment]
@keradus Ah sorry guess I'm getting tired that would be way better 😅

**Comment by keradus** [comment]
2.18 with PHP8 enabled was released. If you would spot any issues with it, raise a net ticket.

I'm leaving this meta-ticket open, as it still contains plenty of ideas for new rules.

**Comment by SpacePossum** [comment]
I'm going to close here as a lot of work has been done and having new dedicated `issues` for each item will be much easier to track going forward. Thanks all for sharing information, thoughts and options, great work :+1:  : )
